

// ----------------------------------------
// ExampleBasic.h
// Generated by Coma.
// ----------------------------------------

#import "BaseClass.h"

@class CustomClass;


@interface ExampleBasic : BaseClass<NSCoding, NSCopying>


/**
 NSString example
 */

@property (strong, nonatomic) NSString* string;


/**
 NSInteger example
 */

@property (assign, nonatomic) NSInteger integer;


/**
 Property with custom object that needs to be deep copied for some reason
 */

@property (strong, nonatomic) CustomClass* custom;


/**
 NSPoint example
 */

@property (assign, nonatomic) NSPoint point;


/**
 NSUInteger example
 */

@property (assign, nonatomic) NSUInteger unsignedInteger;


/**
 NSRect example
 */

@property (assign, nonatomic) NSRect rect;


/**
 NSDate example
 */

@property (strong, nonatomic) NSDate* date;


/**
 BOOL example
 */

@property (assign, nonatomic) BOOL boolean;


/**
 CGFloat example
 */

@property (assign, nonatomic) CGFloat real;



/**
 Returns a list of NSStrings with the names of the properties in it.
 */

+ (NSArray*)propertyNames;

@end
