// ----------------------------------------
// ExampleBasic.m
// Generated by Coma 1.0.
// Do not edit this file - it is automatically generated and your changes will be overwritten.
// ----------------------------------------

#import "ExampleBasic.h"

#import "CustomClass.h"

@implementation ExampleBasic

#pragma mark - Introspection

/**
 Some static arrays containing lists of properties. These are populated once at +initialize time.
 */

static NSArray* sExampleProperties = nil;
static NSArray* sExampleRelationships = nil;
static NSArray* sExampleAttributes = nil;

/**
 Returns a list of NSStrings with the names of the properties in it.
 @return Array of property names.
 */

+ (NSArray*)propertyNames {
    if (!sExampleProperties) {
        sExampleProperties = @[
                             @"boolean",
                             @"custom",
                             @"date",
                             @"integer",
                             @"point",
                             @"real",
                             @"rect",
                             @"string",
                             @"unsignedInteger",
              ];

        if ([super respondsToSelector:@selector(propertyNames)])
            sExampleProperties = [sExampleProperties arrayByAddingObjectsFromArray:[super performSelector:@selector(propertyNames)]];
    }

    return sExampleProperties;
}

/**
 Returns a list of NSStrings with the names of the relationship properties in it.
 @return Array of relationship names.
 */

+ (NSArray*)relationshipNames {
    if (!sExampleRelationships) {
        sExampleRelationships = @[
              ];

        if ([super respondsToSelector:@selector(relationshipNames)])
            sExampleRelationships = [sExampleRelationships arrayByAddingObjectsFromArray:[super performSelector:@selector(relationshipNames)]];
    }

    return sExampleProperties;
}

/**
 Returns a list of NSStrings with the names of the attribute properties in it.
 @return Array of attribute names.
 */

+ (NSArray*)attributeNames {
    if (!sExampleAttributes) {
        sExampleAttributes = @[
                             @"boolean",
                             @"custom",
                             @"date",
                             @"integer",
                             @"point",
                             @"real",
                             @"rect",
                             @"string",
                             @"unsignedInteger",
              ];

        if ([super respondsToSelector:@selector(attributeNames)])
            sExampleAttributes = [sExampleAttributes arrayByAddingObjectsFromArray:[super performSelector:@selector(attributeNames)]];
    }

    return sExampleProperties;
}

#pragma mark - NSCoder

- (void)encodeWithCoder:(NSCoder *)coder {
    [coder encodeBool:self.boolean forKey:@"boolean"];
    [coder encodeObject:self.custom forKey:@"custom"];
    [coder encodeObject:self.date forKey:@"date"];
    [coder encodeInteger:self.integer forKey:@"integer"];
    [coder encodePointAsString:self.point forKey:@"point"];
    [coder encodeDouble:self.real forKey:@"real"];
    [coder encodeRectAsString:self.rect forKey:@"rect"];
    [coder encodeObject:self.string forKey:@"string"];
    [coder encodeInteger:self.unsignedInteger forKey:@"unsignedInteger"];
}

- (id)initWithCoder:(NSCoder *)coder {
    self = [super init];
    if (self) {
      _boolean = [coder decodeBoolForKey:@"boolean"];
      _custom = [coder decodeObjectForKey:@"custom"];
      _date = [coder decodeObjectForKey:@"date"];
      _integer = [coder decodeIntegerForKey:@"integer"];
      _point = [coder decodePointFromStringForKey:@"point"];
      _real = [coder decodeDoubleForKey:@"real"];
      _rect = [coder decodeRectFromStringForKey:@"rect"];
      _string = [coder decodeObjectForKey:@"string"];
      _unsignedInteger = [coder decodeIntegerForKey:@"unsignedInteger"];
    }
    return self;
}

#pragma mark - NSCopying

- (id)copyWithZone:(NSZone *)zone {
    ExampleBasic* copy = [super copyWithZone:zone];
    copy.boolean = self.boolean;
    copy.custom = [self.custom deepCopyWithZone:zone];
    copy.date = [self.date copyWithZone:zone];
    copy.integer = self.integer;
    copy.point = self.point;
    copy.real = self.real;
    copy.rect = self.rect;
    copy.string = [self.string copyWithZone:zone];
    copy.unsignedInteger = self.unsignedInteger;
    return copy;
}



@end
