// ----------------------------------------
// ExampleBasic.h
// Generated by Coma 1.0.
// Do not edit this file - it is automatically generated and your changes will be overwritten.
// ----------------------------------------

#import "BaseClass.h"

@class CustomClass;


@interface ExampleBasic : BaseClass<NSCoding, NSCopying>


/**
 NSString example
 */

// 

@property (strong, nonatomic) NSString* string;


/**
 NSInteger example
 */

// integer

@property (assign, nonatomic) NSInteger integer;


/**
 Property with custom object that needs to be deep copied for some reason
 */

// 

@property (strong, nonatomic) CustomClass* custom;


/**
 NSPoint example
 */

// NSPoint

@property (assign, nonatomic) NSPoint point;


/**
 NSUInteger example
 */

// integer

@property (assign, nonatomic) NSUInteger unsignedInteger;


/**
 NSRect example
 */

// NSRect

@property (assign, nonatomic) NSRect rect;


/**
 NSDate example
 */

// 

@property (strong, nonatomic) NSDate* date;


/**
 BOOL example
 */

// bool

@property (assign, nonatomic) BOOL boolean;


/**
 CGFloat example
 */

// double

@property (assign, nonatomic) CGFloat real;



/**
 Returns a list of NSStrings with the names of the properties in it.
 */


/**
 Returns a list of NSStrings with the names of the properties in it.
 @return Array of property names.
 */

+ (NSArray*)propertyNames;

/**
 Returns a list of NSStrings with the names of the relationship properties in it.
 @return Array of relationship names.
 */

+ (NSArray*)relationshipNames;

/**
 Returns a list of NSStrings with the names of the attribute properties in it.
 @return Array of attribute names.
 */

+ (NSArray*)attributeNames;


@end
