

// ----------------------------------------
// PersonBasic.m
// Generated by Coma.
// ----------------------------------------

#import "PersonBasic.h"
#import "CustomClass.h"

@implementation PersonBasic

static NSArray* sPersonProperties = nil;

+ (NSArray*)propertyNames {
    if (!sPersonProperties) {
        sPersonProperties = @[
                             @"name",
                             @"age",
                             @"custom",
                             
                             ];
    }

    return sPersonProperties;
}

#pragma mark - NSCoder

- (void)encodeWithCoder:(NSCoder *)coder {
    [coder encodeObject:self.name forKey:@"name"];
    [coder encodeObject:@(self.age) forKey:@"age"];
    [coder encodeObject:self.custom forKey:@"custom"];
}

- (id)initWithCoder:(NSCoder *)coder {
    self = [super init];
    if (self) {
        _name = [coder decodeObjectForKey:@"name"];
        [[coder decodeObjectForKey:@"age"] getValue:&_age];
        _custom = [coder decodeObjectForKey:@"custom"];
    }
    return self;
}

#pragma mark - NSCopying

- (id)copyWithZone:(NSZone *)zone {
    PersonBasic* copy = [super copyWithZone:zone];

    copy.name = [self.name copyWithZone:zone];
    copy.age = self.age;
    copy.custom = [self.custom deepCopyWithZone:zone];

    return copy;
}

@end
