// ----------------------------------------
// ExampleUndo.m
// Generated by Coma 1.0.
// Do not edit this file - it is automatically generated and your changes will be overwritten.
// ----------------------------------------

#import "ExampleUndo.h"

@implementation ExampleUndo

- (void)setString:(NSString*)value {
    if (self.string != value) {
        [self.undoManager registerUndoWithTarget:self
                                        selector:_cmd
                                          object:self.string];
        [self.undoManager setActionName:@"Change "];
        [super setString:value];
    }
}


- (void)setInteger:(NSInteger)value {
    if (self.integer != value) {
        [[self.undoManager prepareWithInvocationTarget:self]
         setInteger:self.integer];

        [self.undoManager setActionName:@"Change "];
        [super setInteger:value];
    }
}


- (void)setCustom:(CustomClass*)value {
    if (self.custom != value) {
        [self.undoManager registerUndoWithTarget:self
                                        selector:_cmd
                                          object:self.custom];
        [self.undoManager setActionName:@"Change "];
        [super setCustom:value];
    }
}


- (void)setPoint:(NSPoint)value {
    if (!NSEqualPoints(self.point, value)) {
        [[self.undoManager prepareWithInvocationTarget:self]
         setPoint:self.point];

        [self.undoManager setActionName:@"Change "];
        [super setPoint:value];
    }
}


- (void)setUnsignedInteger:(NSUInteger)value {
    if (self.unsignedInteger != value) {
        [[self.undoManager prepareWithInvocationTarget:self]
         setUnsignedInteger:self.unsignedInteger];

        [self.undoManager setActionName:@"Change "];
        [super setUnsignedInteger:value];
    }
}


- (void)setRect:(NSRect)value {
    if (!NSEqualRects(self.rect, value)) {
        [[self.undoManager prepareWithInvocationTarget:self]
         setRect:self.rect];

        [self.undoManager setActionName:@"Change "];
        [super setRect:value];
    }
}

- (void)setDate:(NSDate*)value {
    if (self.date != value) {
        [self.undoManager registerUndoWithTarget:self
                                        selector:_cmd
                                          object:self.date];
        [self.undoManager setActionName:@"Change "];
        [super setDate:value];
    }
}


- (void)setBoolean:(BOOL)value {
    if (self.boolean != value) {
        [[self.undoManager prepareWithInvocationTarget:self]
         setBoolean:self.boolean];

        [self.undoManager setActionName:@"Change "];
        [super setBoolean:value];
    }
}


- (void)setReal:(CGFloat)value {
    if (self.real != value) {
        [[self.undoManager prepareWithInvocationTarget:self]
         setReal:self.real];

        [self.undoManager setActionName:@"Change "];
        [super setReal:value];
    }
}

@end
