// ----------------------------------------
// ExampleUndo.h
// Generated by Coma 1.0.
// Do not edit this file - it is automatically generated and your changes will be overwritten.
// ----------------------------------------

#import "ExampleBasic.h"

@interface ExampleUndo : ExampleBasic

@property (strong, nonatomic) NSUndoManager* undoManager;

@end
